import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Hero, Products } from "./components";
import { urbanist } from './fonts';
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          <div>{children}</div>
        </CartProvider>
      </body>
    </html>
  );
}
