import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Hero } from "./components";
import { urbanist } from './fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
